In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('/Users/ankurkumar/Downloads/CFPB_Credit_Card_Complaints_2024_Raw.csv')

In [5]:
df.isna().sum()

Date received                       0
Product                             0
Sub-product                         0
Issue                               0
Sub-issue                          63
Consumer complaint narrative    40594
Company public response         37591
Company                             0
State                             213
ZIP code                            0
Tags                            65264
Submitted via                       0
Date sent to company                0
Company response to consumer        0
Timely response?                    0
Complaint ID                        0
dtype: int64

In [8]:
df.describe()

       Complaint ID
count  7.610900e+04
mean   9.578501e+06
std    9.395622e+05
min    8.085114e+06
25%    8.761387e+06
50%    9.516951e+06
75%    1.035062e+07
max    2.358327e+07

In [7]:
df.tail()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
76104,2025-01-01T21:08:15.000Z,Credit card,Store credit card,Incorrect information on your report,Account status incorrect,NaN,NaN,Resurgent Capital Services L.P.,AZ,86004,NaN,Web,2025-01-01T21:34:49.000Z,Closed with explanation,Yes,11343023
76105,2025-01-01T21:43:02.000Z,Credit card,Store credit card,Trouble using your card,Can't use card to make purchases,Goldman Sachs has a {$5000.00} XXXX card open ...,NaN,GOLDMAN SACHS BANK USA,CA,90066,NaN,Web,2025-01-01T21:57:19.000Z,Closed with explanation,Yes,11342691
76106,2025-01-01T22:59:01.000Z,Credit card,General-purpose credit card or charge card,Fees or interest,Unexpected increase in interest rate,My prosper credit card credit limit was over 2...,Company has responded to the consumer and the ...,"Prosper Marketplace, Inc.",TN,37160,NaN,Web,2025-01-15T18:42:09.000Z,Closed with explanation,Yes,11342324
76107,2025-01-01T23:30:36.000Z,Credit card,General-purpose credit card or charge card,Closing your account,Company closed your account,NaN,Company has responded to the consumer and the ...,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",PA,17013,NaN,Web,2025-01-01T23:32:59.000Z,Closed with explanation,Yes,11342321
76108,2025-01-01T23:55:43.000Z,Credit card,General-purpose credit card or charge card,Trouble using your card,Can't use card to make purchases,NaN,NaN,AMERICAN EXPRESS COMPANY,NC,28786,Servicemember,Web,2025-01-02T00:06:19.000Z,Closed with explanation,Yes,11342232

In [6]:
df.head()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,2024-01-01T01:53:02.000Z,Credit card,General-purpose credit card or charge card,Improper use of your report,Reporting company used your report improperly,NaN,NaN,CAPITAL ONE FINANCIAL CORPORATION,GA,31537,NaN,Web,2024-01-01T02:02:02.000Z,Closed with explanation,Yes,8085114
1,2024-01-01T06:23:49.000Z,Credit card,General-purpose credit card or charge card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,On XX/XX/2023 I was wrongfully billed by XXXX....,NaN,CAPITAL ONE FINANCIAL CORPORATION,CA,94538,NaN,Web,2024-01-01T07:09:13.000Z,Closed with explanation,Yes,8086913
2,2024-01-01T13:57:28.000Z,Credit card,Store credit card,Problem with a purchase shown on your statement,Credit card company isn't resolving a dispute ...,The issue with the payment over Synchrony ( TJ...,Company has responded to the consumer and the ...,SYNCHRONY FINANCIAL,NJ,076XX,NaN,Web,2024-01-10T15:35:28.000Z,Closed with explanation,Yes,8086654
3,2024-01-01T15:48:58.000Z,Credit card,General-purpose credit card or charge card,Problem with a company's investigation into an...,Problem with personal statement of dispute,NaN,Company has responded to the consumer and the ...,"BANK OF AMERICA, NATIONAL ASSOCIATION",IN,46235,NaN,Web,2024-01-01T16:12:17.000Z,Closed with explanation,Yes,8086469
4,2024-01-01T16:29:32.000Z,Credit card,Store credit card,Fees or interest,Problem with fees,NaN,NaN,TD BANK US HOLDING COMPANY,GA,30075,NaN,Web,2024-01-01T16:39:47.000Z,Closed with explanation,Yes,8086422

In [9]:
df.isna()

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Submitted via,Date sent to company,Company response to consumer,Timely response?,Complaint ID
0,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76104,False,False,False,False,False,True,True,False,False,False,True,False,False,False,False,False
76105,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False
76106,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
76107,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False
76108,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False

In [12]:
df.nunique()

date_received                   75158
product                             1
sub_product                         2
issue                              15
sub_issue                          55
consumer_complaint_narrative    31769
company_public_response             9
company                           459
state                              59
zip_code                        10374
tags                                3
submitted_via                       4
date_sent_to_company            75672
company_response_to_consumer        4
timely_response                     2
complaint_id                    76109
dtype: int64

In [16]:
print(df["complaint_id"].duplicated().sum())

0

In [17]:
print(df.duplicated().sum())

0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76109 entries, 0 to 76108
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   date_received                 76109 non-null  object
 1   product                       76109 non-null  object
 2   sub_product                   76109 non-null  object
 3   issue                         76109 non-null  object
 4   sub_issue                     76046 non-null  object
 5   consumer_complaint_narrative  35515 non-null  object
 6   company_public_response       38518 non-null  object
 7   company                       76109 non-null  object
 8   state                         75896 non-null  object
 9   zip_code                      76109 non-null  object
 10  tags                          10845 non-null  object
 11  submitted_via                 76109 non-null  object
 12  date_sent_to_company          76109 non-null  object
 13  company_response_to_consumer  76109 non-null  object
 14  timely_response               76109 non-null  object
 15  complaint_id                  76109 non-null  int64
dtypes: int64(1), object(15)
memory usage: 9.3+ MB

In [11]:
df.columns=(
    df.columns
    .str.strip()
    .str.lower()
    .str.replace("?","", regex=False)
    .str.replace(" ", "_",regex=False)
    .str.replace("-", "_", regex=False)
)
print(df.columns)

Index(['date_received', 'product', 'sub_product', 'issue', 'sub_issue',
       'consumer_complaint_narrative', 'company_public_response', 'company',
       'state', 'zip_code', 'tags', 'submitted_via', 'date_sent_to_company',
       'company_response_to_consumer', 'timely_response', 'complaint_id'],
      dtype='object')

In [19]:
df=df.drop_duplicates(subset=["complaint_id"], keep="first")

In [25]:
df["date_received"]=pd.to_datetime(df["date_received"])
df["date_sent_to_company"]=pd.to_datetime(df["date_sent_to_company"])

In [26]:
date_columns=[
    "date_received",
    "date_sent_to_company"
]

In [33]:
df[date_columns].isna().sum()

date_received           0
date_sent_to_company    0
dtype: int64

In [36]:
df=df[
    (df["date_received"]>="2024-01-01")&
    (df["date_received"]<="2025-01-01")
].copy()

In [44]:
categorical_columns=[
"sub_issue",                        
"consumer_complaint_narrative",   
"company_public_response","state","tags"    
]

df[categorical_columns]=(df[categorical_columns].fillna("Not Provided"))

In [45]:
df["zip_code"] = (
    df["zip_code"]
    .astype(str)
    .str.strip()
    .str.replace(".0", "", regex=False)
)

df.loc[
    ~df["zip_code"].str.match(r"^\d{3,5}$", na=False),
    "zip_code"
] = "Not Provided"

In [46]:
df["timely_response"] = (
    df["timely_response"]
    .str.strip()
    .str.title()
)

df.loc[
    ~df["timely_response"].isin(["Yes", "No"]),
    "timely_response"
] = "Unknown"

In [47]:
df["received_year"] = df["date_received"].dt.year
df["received_month"] = df["date_received"].dt.month
df["month_name"] = df["date_received"].dt.month_name()
df["received_quarter"] = "Q" + df["date_received"].dt.quarter.astype(str)
df["day_name"] = df["date_received"].dt.day_name()

df["days_to_send"] = (
    df["date_sent_to_company"] - df["date_received"]
).dt.total_seconds() / 86400

In [48]:
print(df["days_to_send"].describe())

invalid = df[df["days_to_send"] < 0]
print("Invalid date sequence:", len(invalid))

count    75989.000000
mean         0.490288
std          3.571970
min          0.000012
25%          0.004109
50%          0.009271
75%          0.020208
max        445.817326
Name: days_to_send, dtype: float64
Invalid date sequence: 0

In [49]:
df.loc[df["days_to_send"] < 0, "days_to_send"] = pd.NA

In [51]:
print("Final rows:", len(df))
print("Duplicate IDs:", df["complaint_id"].duplicated().sum())
print("Missing values:\n", df.isnull().sum())
print("Date range:", df["date_received"].min(), df["date_received"].max())
print(df["timely_response"].value_counts())

Final rows: 75989
Duplicate IDs: 0
Missing values:
 date_received                   0
product                         0
sub_product                     0
issue                           0
sub_issue                       0
consumer_complaint_narrative    0
company_public_response         0
company                         0
state                           0
zip_code                        0
tags                            0
submitted_via                   0
date_sent_to_company            0
company_response_to_consumer    0
timely_response                 0
complaint_id                    0
received_year                   0
received_month                  0
month_name                      0
received_quarter                0
day_name                        0
days_to_send                    0
dtype: int64
Date range: 2024-01-01 00:04:58+00:00 2024-12-31 23:36:19+00:00
timely_response
Yes    75851
No       138
Name: count, dtype: int64

In [55]:
df.to_csv('~/Desktop/CFPB_Credit_Card_Complaints_2024_Cleaned.csv', index=False)